cities: ["London", "Paris", "Madrid", "Frankfurt am Main", "Zürich", "Moscow", "Amsterdam", "Lisbon", "Rome", "Dublin, Dublin", "Vienna"]
country_codes: ["GBR", "FRA", "ESP", "DEU", "CHE", "RUS", "NLD", "PRT", "ITA", "IRL", "AUT"]
timezones: [0, 1, 1, 1, 1, 3, 1, 0, 1, 0, 1]
summer_time_addition: [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
start_summer_time: [2024, 3, 31]
start_winter_time: [2024, 10, 27]
bucket_name: "tomtom-api-data"