bucket_name: aviations3
cities:
  London: ["LCY", "LGW", "LHR"]
  London: ["LTN", "SEN", "STN"]
  Paris: ["BVA", "CDG", "ORY"]
  Amsterdam: ["AMS"]
  Madrid: ["MAD"]
  Frankfurt: ["FRA", "HHN"]
  Rome: ["FCO"]
  Moscow: ["DME", "SVO", "VKO"]
  Lisbon: ["LIS"]
  Dublin: ["DUB"]
  Vienna: ["VIE"]
  Zurich: ["ZRH"]
