cities: ["London", "Paris", "Madrid", "Frankfurt am Main", "Zürich", "Moscow", "Amsterdam", "Lisbon", "Rome", "Dublin", "Vienna"]
dbname: master
host: database-1.czvyaxqqhlav.us-east-1.rds.amazonaws.com
port: 5432
user: postgres
bucket_name: hslu-project-data
base_path: here/traffic_volume